### PR TITLE
remove where old ingest flow is being called

### PR DESCRIPTION
**Pull request by lewisjkl**
This PR is not to entirely remove the old ingest flow code, but rather just to remove any references to it. Another PR will be coming after this one to actually remove it entirely. I figured it was better to break it up so there were fewer variables at play in each deployment."

### CODE REVIEW

**Comment by lewisjkl** [comment]
E2E tests all pass

**Review by w-aldrich — APPROVED** [review]
Is this something we need to wait a bit longer to see if anyone is using the old flow? If not 🚀

**Comment by lewisjkl** [comment]
> Is this something we need to wait a bit longer to see if anyone is using the old flow? If not 🚀

I gave it 24 hours, which seems reasonable-ish. But what do you think?

**Comment by lewisjkl** [comment]
Tests all pass locally. Merging now.

**Pull request merged**
